### ISSUE TITLE
Please publish latest version

### ISSUE THREAD

**Issue by aereal** [utgwkk/bulkmockgen#6]
The latest version [v0.2.1](https://github.com/utgwkk/bulkmockgen/releases/tag/v0.2.1) does not include changes from https://github.com/utgwkk/bulkmockgen/pull/5.

It causes unnecessary updates on go.sum if the project has migrated to go.uber.org/mock/mockgen.

**Comment by utgwkk** [comment]
I have just published [version 0.2.2](https://github.com/utgwkk/bulkmockgen/releases/tag/v0.2.2). Thank you for your notice!
